title: Possibly a Blog
author: RhynerJ, GitHub user, potential blogger, definitely from Earth
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website is an educational exercise. Author does not vouch for the veracity or relevance of its contents. Continue at own risk.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
